server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clinic?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  jwt:
    secret: "clinicSecretKeyForJwtDemoMustBeAtLeast32CharactersLong12345"
    access-token-expiration-ms: 86400000
    refresh-token-expiration-ms: 604800000
